l_russian:
 CONFIGURATOR_TOOLTIP:0 "Настрой себе игру"
 
 nw_configurator_title:0 "§RКонфигуратор мода§!"
 
 #1 ряд
 ger_title:0 "§HГермания:§!"
 ger_reich:0 "Путь Третьего Рейха"
 ger_kaiser:0 "Путь Кайзера"
 ger_revolt:0 "Путь Револьтрейха"
 ger_democrat:0 "Демократический путь"
 
 hun_title:0 "§HВенгрия:§!"
 hun_hbbrg:0 "Восстановить империю Габсбургов"
 hbbrg_fash:0 "Империя Габсбургов: путь Христианской Империи"
 hbbrg_monarch:0 "Империя Габсбургов: путь Австро-Венгрии"
 hbbrg_danubian:0 "Империя Габсбургов: путь Дунайской федерации/СШЕ"
 
 fra_title:0 "§HФранция:§!"
 fra_little_entente:0 "Путь "Малой антанты""
 fra_go_with_britain:0 "Пробританский путь"
 fra_support_the_left:0 "Коммунистический путь"
 fra_support_the_right:0 "Фашистский путь"
 fra_support_tro:0 "Марксистский путь"
 
 mex_title:0 "§HМексика§!"
 mex_commi:0 "Коммунистический путь"
 mex_troz:0 "Марксистский путь"
 mex_fash:0 "Фашистский путь"
 mex_dem:0 "Демократический путь"
 
 jap_title:0 "§HЯпония§!"
 jap_troz:0 "Марксистский путь"
 jap_commi:0 "Коммунистический путь"
 jap_nokodoha:0 "Борьба с "Кодоха""
 jap_kodoha:0 "Поддержка "Кодоха""
 jap_dem:0 "Демократический путь"
 
 man_title:0 "§HМанчжоу-Го§!"
 man_obedience:0 "Послушание"
 man_aggressiveness:0 "Напористость"
 
 tur_title:0 "§HТурция§!"
 tur_neut_ismet_inenu:0 "Путь Исмета Инёню"
 tur_neut_cakmak:0 "Путь Чакмака"
 tur_dem:0 "Демократический путь"
 tur_fash:0 "Фашистский путь"
 tur_troz:0 "Марксистский путь"
 tur_commi:0 "Коммунистический путь"
 tur_monarch:0 "Монархический путь"
 
 #2 ряд
 can_title:0 "§HКанада:§!"
 can_with_uk:0 "Пробританская политика"
 can_naa:0 "Североамериканский Альянс"
 can_fash:0 "Фашистский путь"
 can_commi:0 "Коммунистический путь"
 
 saf_title:0 "§HЮжная Африка:§!"
 saf_with_uk:0 "Пробританская политика"
 saf_fash:0 "Фашистский путь"
 saf_commi:0 "Коммунистический путь"
 
 raj_title:0 "§HИндия:§!"
 raj_with_uk:0 "Пробританская политика"
 raj_fash:0 "Фашистский путь"
 raj_commi:0 "Коммунистический путь"
 
 ast_title:0 "§HАвстралия:§!"
 ast_with_uk:0 "Пробританская политика"
 ast_self:0 "Самостоятельность"
 ast_fash:0 "Фашистский путь"
 ast_commi:0 "Коммунистический путь"
 
 nzl_title:0 "§HНовая Зеландия:§!"
 nzl_with_uk:0 "Пробританская политика"
 nzl_self:0 "Самостоятельность"
 nzl_fash:0 "Фашистский путь"
 nzl_commi:0 "Коммунистический путь"
 
 generic_all_flag:0 "§MВыбрана настройка в конфигураторе§!"
 
 RESET_CONFIGURATOR_TOOLTIP:0 "Сброс приоритетов"
 ENEMY_SWITCH_TOOLTIP:0 "Активация приоритета AI-игроку"
 GENERIC_TOOLTIP:0 "§RГенерик фокусы будут полностью разблокированы§!"
 RANDOM_TOOLTIP:0 "§RСгенерить рандомные галочки!§!"
 
 NW_conf_on:0 "£trigger_yes"
 NW_conf_off:0 "£trigger_no"
 
 